'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddNewItem

	'''<summary>
	'''lblCreateUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCreateUser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtAddNewItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAddNewItem As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''AddItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AddItem As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lblMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''hdAddItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdAddItem As Global.System.Web.UI.WebControls.HiddenField
End Class
