'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewCategory

	'''<summary>
	'''CAT control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents CAT As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtSearchCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSearchCategory As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnsearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnsearch As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''createCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents createCategory As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gvViewCategory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gvViewCategory As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''lblMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
End Class
