'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewRequisition

    '''<summary>
    '''trlblEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trlblEmpName As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''trtxtEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trtxtEmpName As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''txtEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRequestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateReOpened0_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateReOpened0_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''RequiredFieldValidator77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator77 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ImageButton63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton63 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnSearchRequisition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchRequisition As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddRequisition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRequisition As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvViewRequisition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvViewRequisition As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hAdminRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hAdminRemark As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdITManagerRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdITManagerRemarks As Global.System.Web.UI.WebControls.HiddenField
End Class
