'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewTestCase

    '''<summary>
    '''txtTestCaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestCaseNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchTestCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchTestCase As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''addNewTestCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addNewTestCase As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvTestCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTestCase As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdS_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdS_status As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hd_AppCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hd_AppCategory As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDescription As Global.System.Web.UI.WebControls.HiddenField
End Class
