'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewDetailsDashboard

    '''<summary>
    '''lblGridViewName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGridViewName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvOpenTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOpenTask As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvCloseTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCloseTask As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvAllTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllTicket As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvOpenicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOpenicket As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvCloseTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCloseTicket As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvDailyTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDailyTicket As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvAllPreviousDayTicket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllPreviousDayTicket As Global.System.Web.UI.WebControls.GridView
End Class
