'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewMenuTop

    '''<summary>
    '''txtMenuTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMenuTop As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchMenuTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchMenuTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LinkbtnAssignMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkbtnAssignMenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LinkbtnSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkbtnSubMenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvMenuTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMenuTop As Global.System.Web.UI.WebControls.GridView
End Class
