'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewRoleSubMenu

    '''<summary>
    '''DropListUserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropListUserGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropListMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropListMenu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropListSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropListSubMenu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearchRoleSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchRoleSubMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LinkbtnAssignSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkbtnAssignSubMenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvRoleSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRoleSubMenu As Global.System.Web.UI.WebControls.GridView
End Class
