'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewRoleMenu

    '''<summary>
    '''DropListUserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropListUserGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DropListMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropListMenu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearchRoleMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchRoleMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LinkbtnAssignMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkbtnAssignMenu As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvRoleMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvRoleMenu As Global.System.Web.UI.WebControls.GridView
End Class
